---
layout: cv
title: Grace Wanstrom's Resume
---
# Grace Wanstrom
Accountant, Mathematician, BYUI Graduate.

<div id="webaddress">
<a href="gwanstrom7123@gmail.com">gwanstrom7123@gmail.com</a>
| <a href="https://www.linkedin.com/in/gracewanstrom/">My linkedin page</a>
</div>



## Education

#### Brigham Young University - Idaho
__July 2024__
_Overall GPA: 3.62/4.00_
Bachelor of Science in Accounting
Cluster in Data Science

 - Relevant Courses: Income Taxation l/ll, Audit, Advanced Accounting, Intermediate Financial Accounting l/ll, 
Advanced Spreadsheets 

#### Everett Community College
__June 2020__
Associate of Arts and Science

 - Completed the Running Start program to graduate High School with Associates Degree
 - Graduated from the Ocean Research College Academy program which included challenging advanced course work




## Experience

#### Wipfli LLP | Tax Intern
__Jan. 2024 - Apr. 2024__

 - Prepared tax returns for individuals, trusts, partnerships, s-corporations, and c-corporations using advanced tax 
systems 
 - Trained through the firms training program in CaseWare, CCH Axcess Tax, GoFileRoom, TaxCaddy, Asset Keeper and 
other accounting software
 - Communicated daily with firm associates and clients nationwide to collect relevant information and discuss tax 
principles 

#### Brigham Young University - Idaho | Accounting Tutor
__Sept. 2022 - Dec. 2023__

 - Tutored students struggling in accounting classes ranging from Survey of Accounting to Intermediate Financial 
Accounting 
 - Helped students not in the accounting major understand financial, managerial, and tax accounting in a one-on-one 
setting 
 - Coordinated with students and their schedules in order to set up and conduct one-on-one tutoring sessions that 
would best benefit the student 

#### Brigham Young University - Idaho | Math Study Center Assistant
__Jan. 2023 - Dec. 2023__

 - Managed seventy plus math tutors to coordinate math lab shifts, one-on-one sessions, and meetings using Google 
systems 
 - Trained eighteen new math tutors to confidently work with struggling students in math lab and one-on-one settings
  - Worked closely with and directly under Math Study Center Directors to improve processes within the math lab 

#### Alden Holm & Co. | Tax Intern
__Jan. 2022 - Apr. 2022__

 - Organized and reconciled documents from clients into Excel using Windows software
 - Entered relevant tax information into the Drake system for fifty plus individual and schedule C clients 
 - Worked directly with the firms CPA’s to understand and accurately enter tax information 


## Additional Skills

 - Proficient in: Microsoft Excel, VBA, Python, CaseWare, CCH Axcess Tax, GoFileRoom, TaxCaddy, Drake 
 - Attention to Detail 
 - Problem Solving 
 - Written and Verbal Communication 



<!-- ### Footer

Last updated: July 2024 -->